title: Magnum Solutions Ltd.
uri: https://mag-sol.com/
desc: What's left of the old Magnum Solutions web site. You probably want to look elsewhere.
base: docs
ga4: G-8V1YR6KPDF
redirects:
  - from: /cv/
    to: https://davecross.co.uk/cv/

